---
- name: Restart alerta
  ansible.builtin.service:
    name: alerta
    state: restarted
    daemon_reload: true

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
